import { Beef, Heart, MapPin, Thermometer } from 'lucide-react'

const details = [['Nombre', 'Lora'], ['ID de collar', 'COLLAR-01'], ['Tipo', 'Vaca'], ['Edad', '3 años'], ['Potrero', 'Campo Norte'], ['Asignada desde', '12 abr. 2025']]
const activity = [['Actualización de posición', 'Hace 2 h'], ['Datos de salud recibidos', 'Hace 2 h'], ['Movimiento detectado', 'Hace 3 h'], ['Actualización de posición', 'Hace 5 h']]

export default function DetailsPanel() {
  return (
    <aside className="flex w-full flex-col overflow-hidden rounded-[28px] border border-green-200 bg-white shadow-sm xl:w-96">
      <div className="border-b border-slate-200 p-6"><div className="flex gap-4"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-3xl bg-slate-100"><img src="https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&q=80&w=200&h=200" alt="Lora, una vaca" className="h-full w-full object-cover" /></div><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="text-xl font-semibold text-slate-900">Lora</h2><span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Activa</span></div><p className="mt-1 text-sm text-slate-500">ID de collar: COLLAR-01</p><div className="mt-3 flex flex-wrap gap-2"><span className="flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600"><Beef size={12} />Vaca</span><span className="flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600"><MapPin size={12} />Campo Norte</span></div></div></div></div>
      <div className="flex gap-4 overflow-x-auto border-b border-slate-200 px-6"><button className="border-b-2 border-emerald-600 py-3 text-sm font-medium text-emerald-700">Resumen</button><button className="py-3 text-sm font-medium text-slate-500">Salud</button><button className="py-3 text-sm font-medium text-slate-500">Movimiento</button><button className="py-3 text-sm font-medium text-slate-500">Historial</button></div>
      <div className="space-y-6 p-6"><section><h3 className="mb-4 text-base font-semibold text-slate-900">Información básica</h3><dl className="space-y-3 text-sm">{details.map(([label, value]) => <div key={label} className="flex justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium text-slate-900">{value}</dd></div>)}</dl></section><section><h3 className="mb-4 text-base font-semibold text-slate-900">Últimas métricas de salud</h3><div className="grid grid-cols-2 gap-3"><div className="flex items-center gap-3 rounded-3xl bg-slate-100 p-4"><Thermometer className="text-emerald-600" size={22} /><div><p className="text-xs text-slate-500">Temperatura</p><p className="font-semibold text-slate-900">38,6 °C</p></div></div><div className="flex items-center gap-3 rounded-3xl bg-slate-100 p-4"><Heart className="text-emerald-600" size={22} /><div><p className="text-xs text-slate-500">Frecuencia cardíaca</p><p className="font-semibold text-slate-900">64 lpm</p></div></div></div></section><section><h3 className="mb-3 flex items-center gap-2 text-base font-semibold text-slate-900"><MapPin size={16} className="text-emerald-600" />Ubicación (última actualización)</h3><div className="mb-3 flex justify-between gap-3 text-sm text-slate-500"><span>-34.7321, -58.4326</span><span>Hace 2 h</span></div><div className="relative h-32 overflow-hidden rounded-3xl border border-slate-200 bg-slate-100"><img src="https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=400&h=200" alt="Mapa de la última ubicación de Lora" className="h-full w-full object-cover opacity-70" /><span className="absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white bg-emerald-600 shadow" /></div></section><section><h3 className="mb-4 text-base font-semibold text-slate-900">Actividad reciente</h3><div className="space-y-3">{activity.map(([event, time]) => <div key={`${event}-${time}`} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 text-slate-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />{event}</span><span className="text-slate-500">{time}</span></div>)}</div></section></div>
    </aside>
  )
}
