import { Beef, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react'

const typeStyles = { Vaca: 'bg-emerald-50 text-emerald-700', Toro: 'bg-orange-50 text-orange-700', Vaquillona: 'bg-sky-50 text-sky-700' }

export default function AnimalTable({ animalsData }) {
  return (
    <section className="flex flex-1 flex-col overflow-hidden rounded-[28px] border border-green-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 px-6 py-4 text-sm text-slate-500">Mostrando {animalsData.length} animales</div>
      <div className="flex-1 overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-medium uppercase tracking-[0.12em] text-slate-500"><tr><th className="p-4"><input aria-label="Seleccionar todos los animales" type="checkbox" className="rounded border-slate-300 accent-emerald-600" /></th><th className="p-4">Nombre ↕</th><th className="p-4">ID de collar ↕</th><th className="p-4">Tipo ↕</th><th className="p-4">Edad ↕</th><th className="p-4">Potrero ↕</th><th className="p-4">Visto por última vez ↕</th><th className="p-4">Estado ↕</th><th className="p-4" /></tr></thead><tbody className="text-slate-600">{animalsData.map((animal, index) => <tr key={animal.id} className={`border-b border-slate-100 transition hover:bg-emerald-50/50 ${index === 0 ? 'bg-emerald-50/40' : ''}`}><td className="p-4"><input aria-label={`Seleccionar ${animal.name}`} type="checkbox" className="rounded border-slate-300 accent-emerald-600" /></td><td className="flex items-center gap-2 p-4 font-medium text-slate-900"><Beef size={16} className="text-emerald-600" />{animal.name}</td><td className="p-4">{animal.collar}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-medium ${typeStyles[animal.type]}`}>{animal.type}</span></td><td className="p-4">{animal.age}</td><td className="p-4">{animal.yard}</td><td className="p-4">{animal.lastSeen}</td><td className="p-4"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-500" />{animal.status}</span></td><td className="p-4 text-right"><button aria-label={`Más opciones para ${animal.name}`} className="text-slate-400 transition hover:text-slate-700"><MoreHorizontal size={20} /></button></td></tr>)}</tbody></table></div>
      <div className="flex items-center gap-2 border-t border-slate-200 p-4"><button aria-label="Página anterior" className="rounded-full p-2 text-slate-500 transition hover:bg-slate-100"><ChevronLeft size={20} /></button><button className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-600 text-sm font-medium text-white">1</button><button className="flex h-8 w-8 items-center justify-center rounded-full text-sm text-slate-500 transition hover:bg-slate-100">2</button><button aria-label="Página siguiente" className="rounded-full p-2 text-slate-500 transition hover:bg-slate-100"><ChevronRight size={20} /></button></div>
    </section>
  )
}
